version: 2.1

orbs:
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-buster-node-browsers-legacy # Image that supports browser automation using JS
    resource_class: small # Specifying the size of the instance that is needed to run the tests
    working_directory: ~/project
    steps:
      - checkout
      - run: gem install bundler:2.0.2
      - run: bundle install
      - run:
          name: "Run tests in Chrome"
          command: |
            ruby spec/test_find_professionals.rb

